[build-system]

# Minimum requirements for the build system to execute.
requires = ["setuptools", "wheel", "Cython", "numpy"]  # PEP 508 specifications.
build-backend = "setuptools.build_meta"

[project]
name = "qihmc"
dependencies = ["numpy"]
version = "0.1.0"
