[build-system]

# Minimum requirements for the build system to execute.
requires = ["setuptools", "wheel", "cython", "numpy", "matplotlib", "ipython", "notebook"]  # PEP 508 specifications.
build-backend = "setuptools.build_meta"
